language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: aCslUFyb3lHDkAkCqHnEpwiF5tc29M6shqR9sGhjDd/qda6IUirQYUW1Kb4CHDEAu1Ji0aiAk8NAtMK5catu9UsCC1WkMDUd+PClU4cRilnYRMnxKd8uR0yVi3A3lAocqWrnJ5ES8DVf3WW4z2L3vC6/nJ9GT//nrHHLvAgvo8EgL4pO+oCKUaTSvsVn+/yd/XfUVpjbU6rVrI8hwCGnbynYFUv9fwJEG7kwpNdQekOcLTQUSVM0TKsYVXCLQph4iq/yd2mImKE0BYyMpLBvNNg/OF7fWjONE1v+PkU/FEupdXI/y0It7qjRMamsqi3/CaRailTMV4X1iTxz4bPiGt/UrPR/JozAyf48CGLVbglzFMX8d3IIQ5/gj3yxokY9S8RjAUYFCeq30Jpg7IRud0DRV9rlsj9TbFxNvbnQPwYWeZYQN6BCy/kEEbv9Va+7JPOKUOP75pPrn3sKklbSpzvyixa/xlhlwvk8RlGbgVVhTZiXbUvPChn8vOKSyT0O6TuEfj59SmyADTNSt+nl6hW8RkZstdOiS2kC9FSCh2n0P8cOgniZrVP+uYkr+aZ98b1OCSKgXppUpfdQeGOTymq/oSCK0jTugSLquWsCJb5vdwBfFh2vWXECFs8c41wPbnz6s0ywbpmjOXLc2dclSqqVcMiwUldbALu3NPet7xc=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
