language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: hthdbr1FS+/qW0LqcCLrP3YehXal7Yk23/ulOatnuoExRWJ74D+7mCHUrhnxjrTuaUaKqgcTy+w+1/f1O1nVkJUx6xypQkBXpnPJ0dceFl8Ku953JHiiPJwL0LePB9F13WLB51z+txqfvgXzJmr7y+cmqXLXIfULzjSeILdaOYG00t1hhMNh6LKiNu7Q9J0q+2tP2rEvBn4bZaADTJ/sjq26lTqVp/A1IeyfUUJDbZ2QU806YAvYdCRigbrPMkBsUVH7O0sdteZGaj+3e3ChjUf2GCuv/evALR9jRd1eVDn1zNsYtb/HtN8szhg/IXsEP0wPCbuwx9vVYqMeC9shJi0NLMV3xWSd+J8GH5Opf4NW78RotYBnKrV08YGQtsiuDrhvFaKHwSbfxR1foSFhpiThyEba76zt2HsRVkv0BhBnLmvXjX7ihbaCR95RiQ/3ANr+clAzQhsR5VstESZNLwzF7hLpk5AGE0c8DX4Lg5HZ1xHwzGCsRPT7johueCcNwLUXJmDdZAp9tsP/6BVkw3Uu4IyLmz6av7bF8hW9m4i1vkrYt5pQPTh6XcmOdXfgyYxTGOKqtNXASd+F2YBH6bCfWqbV8UfFIM4G1QsDYLvHkW059W0sfhzq4DP99Dvmw6C9/T+K4s+nyzGYlL3ZohIt3gWhQsMCLcSeSTMV2yE=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
