{{- if .Values.ingress.enabled -}}
{{- $serviceName := .Values.name -}}
{{- $servicePort := or .Values.service.externalPort .Values.service.internalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
