apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
spec:
  ports:
    - port: {{ or .Values.service.externalPort .Values.service.internalPort }}
  selector:
    app: {{ .Values.name }}
